name: Society C.
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#f8f8f8'
    - '#515151'
    - '#929292'
    - '#707070'
  brandStrength: 0.09700057189911604
  lightness: 0.5471496083773673
  saturation: 0
  rhythmicContrast: 0.895662211580202
purpose: []
