name: Society C.
favicon: null
layout_spectrum: 0.5836635367013514
typography_spectrum: 0.22919110511429608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09700057189911604
  lightness: 0.5471496083773673
  saturation: 0.8139236259739846
  rhythmicContrast: 0.895662211580202
purpose: []
